application: kurebio-test-xxxxx
service: front
version: 1
runtime: go
api_version: go1.8
threadsafe: yes

instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 10
  min_pending_latency: 3000ms
  max_pending_latency: 5000ms
  max_concurrent_requests: 50

includes:
- ../inc_variables.yaml
- ../inc_secret.yaml

nobuild_files: vendor/

handlers:
- url: /cron_frontend/.*
  script: _go_app
  login: admin

- url: /api/.*
  script: _go_app
  secure: always