application: kurebio-test-xxxxx
service: pages
version: 1
runtime: python27
api_version: 1
threadsafe: yes

instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 10
  min_pending_latency: 3000ms
  max_pending_latency: 5000ms
  max_concurrent_requests: 50

includes:
- ../inc_variables.yaml
- ../inc_secret.yaml

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app